"""empty message

Revision ID: db4ba6e6734b
Revises:
Create Date: 2025-12-10 22:23:40.871708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db4ba6e6734b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bidders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bidders_country"), "bidders", ["country"], unique=False)
    op.create_index(op.f("ix_bidders_id"), "bidders", ["id"], unique=False)
    op.create_table("supplies", sa.Column("id", sa.String(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_supplies_id"), "supplies", ["id"], unique=False)
    op.create_table(
        "supply_bidder",
        sa.Column("supply_id", sa.String(), nullable=False),
        sa.Column("bidder_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["bidder_id"], ["bidders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supply_id"], ["supplies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("supply_id", "bidder_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supply_bidder")
    op.drop_index(op.f("ix_supplies_id"), table_name="supplies")
    op.drop_table("supplies")
    op.drop_index(op.f("ix_bidders_id"), table_name="bidders")
    op.drop_index(op.f("ix_bidders_country"), table_name="bidders")
    op.drop_table("bidders")
    # ### end Alembic commands ###
